# Generated by Django 4.2.1 on 2023-08-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Equ_States",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=15, verbose_name="设备编号")),
                ("life_limit", models.IntegerField(verbose_name="使用年限")),
                ("time_touse", models.DateTimeField(verbose_name="投用时间")),
                ("status", models.CharField(max_length=10, verbose_name="目前状态")),
            ],
            options={
                "verbose_name": "设备状态",
                "verbose_name_plural": "设备状态",
            },
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=15, verbose_name="设备编号")),
                ("name", models.CharField(max_length=10, verbose_name="设备名称")),
                ("type", models.CharField(max_length=10, verbose_name="设备型号")),
                ("manufacture", models.CharField(max_length=10, verbose_name="生产商")),
                (
                    "info",
                    models.TextField(
                        blank=True, max_length=300, null=True, verbose_name="设备描述"
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="设备图片"
                    ),
                ),
            ],
            options={
                "verbose_name": "设备信息",
                "verbose_name_plural": "设备信息",
            },
        ),
        migrations.CreateModel(
            name="Order_Ids",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("RP", models.IntegerField()),
                ("RR", models.IntegerField()),
                ("OFF", models.IntegerField()),
                ("RA", models.IntegerField()),
            ],
            options={
                "verbose_name": "每日工单数量",
                "verbose_name_plural": "每日工单数量",
            },
        ),
        migrations.CreateModel(
            name="Repair_Accept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orderid", models.CharField(max_length=15, verbose_name="单号")),
                ("code", models.CharField(max_length=10, verbose_name="设备编号")),
                ("name", models.CharField(max_length=10, verbose_name="设备名称")),
                ("type", models.CharField(max_length=10, verbose_name="验收类型")),
                ("info", models.TextField(max_length=100, verbose_name="维修记录")),
                ("date", models.DateTimeField(verbose_name="验收日期")),
            ],
            options={
                "verbose_name": "设备维修验收表",
                "verbose_name_plural": "设备维修验收表",
            },
        ),
        migrations.CreateModel(
            name="Repair_Manage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orderid", models.CharField(max_length=15, verbose_name="单号")),
                ("type", models.CharField(max_length=10, verbose_name="类型")),
                ("status", models.IntegerField(verbose_name="状态")),
                ("date1", models.DateTimeField(verbose_name="审批日期1")),
                ("date2", models.DateTimeField(verbose_name="审批日期2")),
                ("memo", models.TextField(blank=True, null=True, verbose_name="备注")),
            ],
            options={
                "verbose_name": "设备维修管理表",
                "verbose_name_plural": "设备维修管理表",
            },
        ),
        migrations.CreateModel(
            name="Repair_Off_Req",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orderid", models.CharField(max_length=15, verbose_name="单号")),
                ("code", models.CharField(max_length=10, verbose_name="设备编号")),
                ("name", models.CharField(max_length=10, verbose_name="设备名称")),
                ("type", models.CharField(max_length=10, verbose_name="关停类型")),
                ("info", models.TextField(max_length=100, verbose_name="关停原因")),
                ("start", models.DateTimeField(verbose_name="预计开始日期")),
                ("end", models.DateTimeField(verbose_name="预计结束日期")),
                ("date", models.DateTimeField(verbose_name="申请日期")),
            ],
            options={
                "verbose_name": "设备关停申请表",
                "verbose_name_plural": "设备关停申请表",
            },
        ),
        migrations.CreateModel(
            name="Repair_Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orderid", models.CharField(max_length=15, verbose_name="单号")),
                ("code", models.CharField(max_length=10, verbose_name="设备编号")),
                ("name", models.CharField(max_length=10, verbose_name="设备名称")),
                ("type", models.CharField(max_length=10, verbose_name="维修类型")),
                ("erro", models.CharField(max_length=100, verbose_name="故障说明")),
                ("info", models.TextField(max_length=100, verbose_name="维修说明")),
                ("start", models.DateTimeField(verbose_name="预计开始日期")),
                ("end", models.DateTimeField(verbose_name="预计结束日期")),
                ("cost", models.IntegerField(verbose_name="预计检修费用")),
                ("date", models.DateTimeField(verbose_name="申请日期")),
            ],
            options={
                "verbose_name": "设备维修申请表",
                "verbose_name_plural": "设备维修申请表",
            },
        ),
        migrations.CreateModel(
            name="Repair_Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orderid", models.CharField(max_length=15, verbose_name="单号")),
                ("code", models.CharField(max_length=10, verbose_name="设备编号")),
                ("name", models.CharField(max_length=10, verbose_name="设备名称")),
                ("type", models.CharField(max_length=10, verbose_name="检修类别")),
                ("info", models.TextField(max_length=100, verbose_name="主要检修内容")),
                ("start", models.DateTimeField(verbose_name="预计开始日期")),
                ("end", models.DateTimeField(verbose_name="预计结束日期")),
                ("cost", models.IntegerField(verbose_name="预计检修费用")),
                ("date", models.DateTimeField(verbose_name="制定日期")),
            ],
            options={
                "verbose_name": "设备维修计划表",
                "verbose_name_plural": "设备维修计划表",
            },
        ),
    ]
