# Generated by Django 4.2.1 on 2023-08-05 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("maintenance", "0001_initial"),
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="repair_manage",
            name="acceptor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="accept_orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="验收人",
            ),
        ),
        migrations.AddField(
            model_name="repair_manage",
            name="approver1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="approve_orders1",
                to=settings.AUTH_USER_MODEL,
                verbose_name="审批人1",
            ),
        ),
        migrations.AddField(
            model_name="repair_manage",
            name="approver2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="approve_orders2",
                to=settings.AUTH_USER_MODEL,
                verbose_name="审批人2",
            ),
        ),
        migrations.AddField(
            model_name="repair_manage",
            name="maker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="make_orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="发起人",
            ),
        ),
        migrations.AddField(
            model_name="equ_states",
            name="purchaser",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="equipments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="采购人",
            ),
        ),
        migrations.AddField(
            model_name="equ_states",
            name="use_dep",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="equipments",
                to="organization.structure",
                verbose_name="使用部门",
            ),
        ),
    ]
